"""add superadmin role

Revision ID: 0002_add_superadmin_role
Revises: 0001_initial_schema
Create Date: 2026-05-13
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_add_superadmin_role"
down_revision: str | None = "0001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # SQL Server stores enums as VARCHAR — just widen the column to accept new value.
    # Alembic will not fail even if the enum type does not exist on MSSQL.
    # The ORM-level StrEnum already validates values; here we just ensure the column
    # accepts the new string.
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "mssql":
        # Drop the check constraint that limits role values (if any), then re-create it.
        # The constraint name was auto-generated by SQLAlchemy on create_table.
        # Safest approach: alter the column type (no-op on MSSQL VARCHAR) and
        # let the new ORM enum handle validation at app level.
        op.execute("ALTER TABLE users ALTER COLUMN role NVARCHAR(20) NOT NULL")
    else:
        # PostgreSQL: alter enum type
        op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'SuperAdmin'")


def downgrade() -> None:
    # Removing an enum value is destructive — update any SuperAdmin rows to Admin first.
    op.execute("UPDATE users SET role = 'Admin' WHERE role = 'SuperAdmin'")
